services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: iliad-test
    container_name: iliad-test
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravelnet
    environment:
      - "APP_NAME=Iliad Test"
      - "DB_CONNECTION=mysql"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=iliad"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=iliad"
  
  db:
    image: mysql:8.0
    container_name: iliad-test-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: iliad
      MYSQL_ROOT_PASSWORD: iliad
    networks:
      - laravelnet
    volumes:
      - dbdata:/var/lib/mysql
  
  nginx:
    image: nginx:alpine
    container_name: iliad-test-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - laravelnet
  
networks:
  laravelnet:
    driver: bridge

volumes:
  dbdata:
    driver: local